
export const AllProps = {
	browserWindow: false,
	code: '',
	codeBlockRadius: '0.5rem',
	copyButton: true,
	copyIcons: true,
	copyTab: true,
	copyFailedText: 'Copy failed!',
	copyText: 'Copy Code',
	copySuccessText: 'Copied!',
	floatingTabs: true,
	height: 'auto',
	highlightjs: false,
	indent: 2,
	label: '',
	lang: 'javascript',
	maxHeight: 'auto',
	persistentCopyButton: false,
	prismjs: false,
	prismPlugin: false,
	runTab: false,
	runText: 'Run',
	tabGap: '0.25rem',
	tabs: false,
	theme: 'neon-bunny',
};
